-- MySQL Script generated by MySQL Workbench
-- 01/02/18 20:21:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tompuglisi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tompuglisi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tompuglisi` DEFAULT CHARACTER SET utf8 ;
USE `tompuglisi` ;

-- -----------------------------------------------------
-- Table `tompuglisi`.`quotes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tompuglisi`.`quotes` ;

CREATE TABLE IF NOT EXISTS `tompuglisi`.`quotes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quote` VARCHAR(255) NOT NULL,
  `author` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
